[versions]
slf4j = "2.0.17"
kaributools = "0.27"
karibudsl = "2.4.0"
junit5 = "6.0.1"
# Check the newest Vaadin version at https://github.com/vaadin/platform/tags
vaadin24 = "25.0.5"
vaadin24_spring = "25.0.5"
vaadin24next = "25.1.0-alpha5"
vaadin24next_spring = "25.1.0-alpha5"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kaributools = { module = "com.github.mvysny.karibu-tools:karibu-tools", version.ref = "kaributools" }
kaributools23 = { module = "com.github.mvysny.karibu-tools:karibu-tools-23", version.ref = "kaributools" }
karibudsl = { module = "com.github.mvysny.karibudsl:karibu-dsl", version.ref = "karibudsl" }
karibudsl23 = { module = "com.github.mvysny.karibudsl:karibu-dsl-v23", version.ref = "karibudsl" }
junit-jupiterapi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
vaadin-v24-all = { module = "com.vaadin:vaadin", version.ref = "vaadin24" }
vaadin-v24-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24" }
vaadin-v24-spring = { module = "com.vaadin:vaadin-spring", version.ref = "vaadin24_spring" }
vaadin-v24next-all = { module = "com.vaadin:vaadin", version.ref = "vaadin24next" }
vaadin-v24next-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24next" }
vaadin-v24next-spring = { module = "com.vaadin:vaadin-spring", version.ref = "vaadin24next_spring" }
classgraph = "io.github.classgraph:classgraph:4.8.151"
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"
groovy = "org.apache.groovy:groovy:4.0.29"
hibernate-validator = "org.hibernate.validator:hibernate-validator:9.1.0.Final"
jakarta-el-api = "jakarta.el:jakarta.el-api:5.0.1"
spring-boot-starter-test = "org.springframework.boot:spring-boot-starter-test:4.0.1"
spring-boot-starter-web = "org.springframework.boot:spring-boot-starter-web:4.0.1"
fake-servlet5 = "com.github.mvysny.fake-servlet:fake-servlet5:1.3"
